### PR TITLE
Add cache and replay for the web graph

### PR DESCRIPTION
**Pull request by ertrzyiks**
Thanks to that when you reload the page, the graph immediately display some data.

PS. I'm not really into streams, don't know if it's a correct solution, but I haven't found anything better though

### CODE REVIEW

**Comment by alanshaw** [comment]
I like the idea, I think the issue is that all connected clients will receive the replay data whenever a new client connects. You'd need to create a new through stream in the shoe connection handler to only send the replay data to a new client.

Also, the code should handle the case where `bufferSize` is 0.

**Comment by ertrzyiks** [comment]
Thanks for tips @alanshaw, I will try to improve the code

**Comment by ertrzyiks** [comment]
I've fixed the problem with a new client connected, but when I refresh graf page around 10 times, node js prints a warning:

```
(node:75628) Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
```

I will debug it tomorrow

**Comment by ertrzyiks** [comment]
@alanshaw ok, I think it's ready. I was overdoing it before.

**Comment by alanshaw** [comment]
LGTM!

**Pull request merged**
